apiVersion: v1
name: firehose-chart
description: A Helm chart for the ACK service controller for Amazon Kinesis Data Firehose (Firehose)
version: 0.2.0
appVersion: 0.2.0
home: https://github.com/aws-controllers-k8s/firehose-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/firehose-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: Firehose Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/firehose-maintainer
keywords:
  - aws
  - kubernetes
  - firehose
